import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

src_root = 'src'

# Mapeamento de emojis corrompidos para corretos
replacements = {
    '😀"Š': '📊',
    '👥‘—😀Ž"': '👥',
    '😀"…': '📅',
    "😀'š": '💙',
    '😀"Ž': '🔍',
    '😀"ˆ': '📋',
    "😀'¬": '💬',
    '👥­': '🧭',
    '😀"Œ': '📢',
    '😀"': '👥',
    '😀Ž"': '🔍',
    '😀\'': '👁',
    '😀"': '📊',
    'ðŸ"': '🔒',
    'ðŸ\'': '👤',
    'ðŸ§': '👥',
    'ðŸ"…': '📅',
    "ðŸ'š": '💙',
    'ðŸ"Ž': '🔍',
    'ðŸ"ˆ': '📋',
    "ðŸ'¬": '💬',
    'ðŸ§­': '🧭',
    'ðŸ"Œ': '📢',
    'ðŸ"': '👥',
    'ðŸŽ"': '🔍',
    'ðŸ‘': '👤',
    'ðŸ"': '🔒',
    'ðŸ¤': '🤝',
    'ðŸ§': '🧠',
    'ðŸ™': '🙈',
    'ðŸ‘�': '👁',
    '\x81': '',
    '\x90': '',
    '\x8f': '',
    '\x9f': '',
    '\x9c': '',
    '\x9d': '',
    '\xa0': ' ',
    '”€': '—',
    'â€': '—',
    'â€”': '—',
    'â€“': '–',
    'â€¦': '...',
    'â€œ': '"',
    'â€': '"',
    'â€˜': "'",
    'â€™': "'",
    'â†’': '→',
    'âž•': '➕',
    'â�§': '⏳',
    'â�€': '⏳',
    'â€¡': '‡',
    'â€¢': '•',
    'â€°': '‰',
    'â€¹': '‹',
    'â€º': '›',
    'â‚¬': '€',
    'â„¢': '™',
    'âˆ': 'ˆ',
    'â‹': '‹',
    'âŸ': '›',
    'â™': '♪',
    'â—': '●',
    'â•': '•',
    'âš': '⚡',
    'âœ': '✖',
    'â–': '–',
    'â˜': '˜',
    'Ã§': 'ç', 'Ã£': 'ã', 'Ã³': 'ó', 'Ã¡': 'á', 'Ã©': 'é',
    'Ã­': 'í', 'Ãº': 'ú', 'Ãª': 'ê', 'Ã´': 'ô', 'Ã¼': 'ü',
    'Ã±': 'ñ', 'Ã§Ãµ': 'ções', 'Ã§Ã£': 'ção',
    'Ã‡': 'Ç', 'Ãƒ': 'Ã', 'Ã“': 'Ó', 'Ã': 'Á', 'Ã‰': 'É',
    'Ã': 'Í', 'Ãš': 'Ú', 'ÃŠ': 'Ê', 'Ã”': 'Ô', 'Ãœ': 'Ü',
    'Ã‘': 'Ñ',
    'Â': '', '\xa0': ' ', 'Â ': '',
    'NAVEGAÃ‡ÃƒO': 'NAVEGAÇÃO',
    'OrientaçÃµes': 'Orientações',
    'ConfiguraçÃµes': 'Configurações',
    'Indicadores e exportaÃ§Ãµes': 'Indicadores e exportações',
    'requisiÃ§Ãµes': 'requisições',
    'subsequÃªncias': 'subsequências',
    'requisiÃ§Ã£o': 'requisição',
    'horÃ¡rio': 'horário',
    'InstÃ¢ncia': 'Instância',
    'notificaÃ§Ãµes': 'notificações',
    'fila de operaÃ§Ãµes': 'fila de operações',
    'operaÃ§Ãµes': 'operações',
    'Acesso dinÃ¢mico': 'Acesso dinâmico',
    'instÃ¢ncia': 'instância',
    'InstÃ¢ncia global': 'Instância global',
    'InstÃ¢ncia Ãºnica': 'Instância única',
    'Ãºltima': 'última',
    'Adiciona Ã ': 'Adiciona à ',
    'Adiciona Ã\xa0': 'Adiciona à ',
    'operaÃ§Ã£o': 'operação',
    'fila de operaÃ§Ã£o': 'fila de operação',
    'NÃ£o': 'Não',
    'opÃ§Ãµes': 'opções',
    'parÃ¢metro': 'parâmetro',
    'pÃ¡gina': 'página',
    'aÃ§Ãµes': 'ações',
    'funÃ§Ãµes': 'funções',
    'Ã¡rea': 'área',
    'InstÃªncia': 'Instância',
    'requisiÃ§Ãµes API': 'requisições API',
    'requisiÃ§Ãµes subsequentes': 'requisições subsequentes',
    'requisiÃ§Ãµes POST': 'requisições POST',
    'notificaÃ§Ãµes de ajuda': 'notificações de ajuda',
    'notificaÃ§Ãµes de alertas': 'notificações de alertas',
    'orientaÃ§Ãµes': 'orientações',
    'listar orientaÃ§Ãµes': 'listar orientações',
    'buscar orientaÃ§Ãµes': 'buscar orientações',
    'total} orientaÃ§Ãµes': 'total} orientações',
    'listar orientaÃ§Ãµes locais': 'listar orientações locais',
    'opÃ§Ãµes estilizado': 'opções estilizado',
    'funÃ§Ãµes pÃºblicas': 'funções públicas',
    'aÃ§Ãµes.': 'ações.',
    'semÃ¢nticos': 'semânticos',
    'especÃficos': 'específicos',
    'Ã¡REA DE CONTEÃšDO': 'ÁREA DE CONTEÚDO',
    'conteÃºdo': 'conteúdo',
    'CONTEÃšDO': 'CONTEÚDO',
    'pÃºblicas': 'públicas',
    'Ãºnico': 'único',
    'Ãºnicos': 'únicos',
    'Ãºnica': 'única',
    'Ã§Ãµes': 'ções',
    'Ã§Ã£o': 'ção',
    'Ã§Ãµ': 'ções',
    'Ã£o': 'ão',
    'Ãµes': 'ões',
    'Ã¡': 'á',
    'Ã©': 'é',
    'Ã': 'í',
    'Ã³': 'ó',
    'Ãº': 'ú',
    'Ã¢': 'â',
    'Ãª': 'ê',
    'Ã´': 'ô',
    'Ã¼': 'ü',
    'Ã±': 'ñ',
    'Ã‡': 'Ç',
    'Ãƒ': 'Ã',
    'Ã“': 'Ó',
    'Ã': 'Á',
    'Ã‰': 'É',
    'Ã': 'Í',
    'Ãš': 'Ú',
    'ÃŠ': 'Ê',
    'Ã”': 'Ô',
    'Ãœ': 'Ü',
    'Ã‘': 'Ñ',
    'Ã ': ' ',
    'Ã': 'A',
}

fixed = 0
for root, dirs, files in os.walk(src_root):
    for name in files:
        if not name.endswith('.py'):
            continue
        filepath = os.path.join(root, name)
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()

        original = content
        for old, new in replacements.items():
            if old in content:
                content = content.replace(old, new)

        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            fixed += 1
            print(f'Fixed: {filepath}')

print(f'\nTotal fixes: {fixed}')
